### DISCUSSION TITLE
Change Main Sidebery Button Display

### DISCUSSION THREAD

**Discussion by n1x9** [mbnuqw/sidebery#1085] [Q&A] [answered]
Good day all!

I was wondering if it was possible to change the display of the main Sidebery button to either just show the icon or add different text?

Current Button Display
![Sidebery 1](https://github.com/mbnuqw/sidebery/assets/76404152/1316c1a9-cdff-4b93-8e88-6ecd198ea3d2)

Desired Button Display
![Sidebery 2](https://github.com/mbnuqw/sidebery/assets/76404152/9644b411-07ed-4a48-8003-986e9a261f5e)

Please advise. Thanks!

**Comment by mbnuqw** [comment, marked as answer]
It's a part of Firefox UI, so Sidebery can't change anything inside this block. You can try to use userChrome.css hack to change it (ask [here](https://www.reddit.com/r/FirefoxCSS/)), but I doubt it's possible to replace dropdown to icons here. In v5 (current beta) you can show the name of an active panel instead of just "Sidebery".

Personally, I use this userChrome.css hack to decrease size of this block:
```css
/**
 * Decrease size of header
 */
#sidebar-header {
  font-size: 1.2em !important;
  padding: 2px 6px 2px 3px !important;
}
#sidebar-header #sidebar-close {
  padding: 3px !important;
}
#sidebar-header #sidebar-close .toolbarbutton-icon {
  width: 14px !important;
  height: 14px !important;
  opacity: 0.6 !important;
}
```
Before
![screenshot-2023-06-28 17:41:49](https://github.com/mbnuqw/sidebery/assets/6276694/20d8ac7b-ac09-43d1-9844-92ae033aab4f)

After
![screenshot-2023-06-28 17:38:59](https://github.com/mbnuqw/sidebery/assets/6276694/8121e038-a17b-4989-8891-55e31e1cdd10)
