### DISCUSSION TITLE
Is there a way to remove the "Folded tab/group" symbol (the "greater than" symbol)

### DISCUSSION THREAD

**Discussion by JohnVKRDam** [mbnuqw/sidebery#1236] [General]
As written in the post title, is there a way to remove the folded tab/group symbol?

The reason I would like to get rid of it, is because when I fold a set of tabs / group, I can no longer see the Url's website icon. It is way easier to quickly identify tabs if I can see the website icon. The folded tab/group symbol is of no use to me in this regard.

Plus, I can already see that there are more tabs beneath it, because the NUMBER OF SUB-ITEMS is displayed on the folded tab/group. I know you can disable the display of the number of sub-items, so I understand the basic need for the folded tab/group greater than symbol.

Is there a piece of custom CSS code that I can use for this? I could not find a setting anywhere in the regular settings and/or the Styles Editor.

I hope someone can help me. It would greatly improve my "Sidebery Life" ;)
Thanks in advance!

Kind regards,
John

p.s. I am THOROUGHLY enjoying Sidebery!! It's the best thing since sliced bread, for me anyway! :)

**Comment by mbnuqw** [comment]
It's planned to add more options of how the folded branch is rendered, you can track this issue: https://github.com/mbnuqw/sidebery/issues/794

But for now, use this custom CSS snippet (in Sidebery style editor):
```css
.Tab[data-parent="true"][data-folded="true"] .body .fav:not(:hover) .exp > svg {
  opacity: 0;
}

.Tab[data-parent="true"][data-folded="true"] .body .fav:not(:hover) .fav-icon {
  opacity: 1;
}
```

and check snippets in #794
