### DISCUSSION TITLE
Show marks for sub-tree levels as dots?

### DISCUSSION THREAD

**Discussion by BurntFood** [mbnuqw/sidebery#1260] [Q&A] [answered]
I preferred having the indicator show as dots.
Don't see any options to return it to that instead of lines in v5.
Would appreciate it greatly if I were told how to change it.

**Comment by mbnuqw** [comment, marked as answer]
Use this custom CSS:
```css
#root .Tab[data-pin="false"]:not([data-lvl="0"]) .body:after {
  height: 4px;
  width: 4px;
  border-radius: 50%;
  top: calc(50% - 2px);
    left: calc(var(--tabs-indent) * -0.5 - 2px);
    background-image: none;
  background-color: var(--tabs-normal-fg);
}
```
Open `Sidebery settings >> Styles editor` and paste these CSS styles into the text field (the right column)
