### DISCUSSION TITLE
Change color of text for unloaded tabs

### DISCUSSION THREAD

**Discussion by rieje** [mbnuqw/sidebery#1572] [Q&A] [answered]
Is it possible to change the color of text for unloaded tabs? It's a muted gray and I would like something lighter. In the Styles editor I see Active and Normal (i.e. loaded) tabs, but not for unloaded tabs.

**Comment by mbnuqw** [comment, marked as answer]
Use this custom style:
```css
.Tab {
  --tabs-discarded-favicon-opacity: .5;
  --tabs-discarded-title-opacity: .7;
}
#root .Tab[data-discarded="true"] > .body > .fav {
  opacity: var(--tabs-discarded-favicon-opacity);
}
#root .Tab[data-discarded="true"] > .body > .t-box,
#root .Tab[data-discarded="true"] > .body > .ctx {
  opacity: var(--tabs-discarded-title-opacity);
}
```

Also, these vars were added in #1553, so they already available in v5.2.0.5
