### DISCUSSION TITLE
Tips on improving scrollbar + indented tabs?

### DISCUSSION THREAD

**Discussion by rieje** [mbnuqw/sidebery#1581] [Q&A]
When scrollbar is on the right, it [overlaps the close button](https://0x0.st/XiDG.png) and often times I end up clicking the scrollbar instead of closing the tab which is annoying (I zoomed in on the pic). I was looking into CSS solutions but was not successful.

Moving the scrollbar to the left prevents this issue; however, [it makes the indent marker very hard to see](https://0x0.st/XiDk.png). Increasing indent (--tabs-indent) is not appropriate because to increase it to a level that makes it visually obvious, it also increases the indent of the rest of the tree significantly, reducing the tab title by a lot within the sidebar. Modifying inner gap (--tabs-inner-gap) does not affect the indent marker.

The tabs close button should remain on the right and I prefer the scrollbar to be on the right as well but I'm currently settling with what's shown on the second pic (scrollbar on the left, hard to to see first indent marker).

**Comment by mbnuqw** [comment]
Track the #844. For workaround for scrollbar on the right:
```css
.TabsPanel > .ScrollBox > .bottom-shadow[data-show="true"] ~ .scroll-container,
.TabsPanel > .ScrollBox > .top-shadow[data-show="true"] ~ .scroll-container {
  padding-right: 8px;
}
```
