### DISCUSSION TITLE
How to change indent lines colors and opacity

### DISCUSSION THREAD

**Discussion by haShinui** [mbnuqw/sidebery#1742] [Q&A]
I mean those lines here, couldnt find anything online
![image](https://github.com/user-attachments/assets/6ebc5a7f-d2a2-4b2a-804d-7c0e5d23b54e)

**Comment by jamespeilunli** [comment]
Go to "Styles editor" in Sidebery settings and add this to the custom CSS section:

```css
/* indent lines */
#root .Tab[data-pin="false"]:not([data-lvl="0"]) .body:after {
  width: 1px;
  top: -1px;
  background-color: var(--tabs-activated-fg);
  opacity: 0.7;
}
```
