### DISCUSSION TITLE
How to move the tab counter for folded tabs?

### DISCUSSION THREAD

**Discussion by klazoklazo** [mbnuqw/sidebery#1751] [Q&A] [answered]
Okay so I tend to have quite a few tabs open within a single branch, but I'm not sure what the CSS could possibly be for moving around the tab counter.

Right now, having the tab counter farther to the left or centered with the favicon would be ideal IMO, since right now it tends to interfere with the tab's title.

![image](https://github.com/user-attachments/assets/2989a676-b79d-478b-b9a9-d1dbc3403966)

I also use double line titles, which conflict even harder with the tab counters.

![image](https://github.com/user-attachments/assets/5a6360db-e21d-4c2d-813a-bcea4233667c)

**Comment by ChilledMoth** [comment, marked as answer]
Try increasing the values of the '--tabs-inner-gap' and '--tabs-height' variables to make up some room, e.g.:
```css
#root.root {--tabs-inner-gap: 10px;}
#root.root {--tabs-height: 36px;}
```
To place the counter centered beneath the favicon, try the following rule:
```css
.Tab .child-count {
  width: 16px;
  right: 0px;
  bottom: -10px;
  text-align: center;
}
```
