### DISCUSSION TITLE
Colors to Bookmarks Folders and Icons for Bookmarks pages

### DISCUSSION THREAD

**Discussion by talonsavo** [mbnuqw/sidebery#1814] [Q&A]
Hey guys,

I have two questions.

(1) Is it possible to 'preload' my bookmarks' icons in sidebery's panel? Youtube's icon for instance. 
(2) Is it possible to color folders' icon within sidebery's panel?

I've uploaded a screenshot of all my greyed sidebery's panel bookmarks that don't have their proprietary icons loaded 
VS how it is on my firefox default toolbar where I was able, following a tutorial, to color my folder icons.

![2024-09-27 04_47_23-New Discussion · mbnuqw_sidebery — Mozilla Firefox](https://github.com/user-attachments/assets/3b51bd96-2cb1-43b4-844f-7b66d419e109)
VS
![2024-09-27 04_47_50-New Discussion · mbnuqw_sidebery — Mozilla Firefox](https://github.com/user-attachments/assets/3bafaf07-6bc0-43b7-966a-f9378afdf237)

Thanks a lot,
G

**Comment by talonsavo** [comment]
Nobody knows?:(

**Comment by ChilledMoth** [comment]
Re: (1) Favicons are cached. Opening a bookmark should create/refresh the individual cache entry. The favicon cache can be populated automatically for all bookmarks by using the 'Fetch favicons' button in the bookmarks section on the settings page. If it got corrupted for some reason, it can also be recreated by using the 'Sideberys data' button in the general section and manually deleting everything starting with 'fav'.

Re: (2) It's possible using custom CSS rules, which can be added with the styles editor on the settings page. 

To colorize all folder icons:
```css
.BookmarkNode[data-type="folder"] > .body > .fav > svg {
  fill: #c68317;
  opacity: 1;
}
```
Note: Setting opacity isn't strictly necessary, but it's set to 0.5 by default and colors will be off otherwise.

To colorize all folder titles:
```css
.BookmarkNode[data-type="folder"] > .body > .title {
  color: #c68317;
}
```

To colorize icons of specific folders:
```css
.BookmarkNode[data-type="folder"] > .body[title="Perso"] > .fav > svg,
.BookmarkNode[data-type="folder"] > .body[title="Films"] > .fav > svg,
.BookmarkNode[data-type="folder"] > .body[title="Presse"] > .fav > svg {
  fill: #c68317;
  opacity: 1;
}

.BookmarkNode[data-type="folder"] > .body[title="Shopping"] > .fav > svg,
.BookmarkNode[data-type="folder"] > .body[title="Temp"] > .fav > svg {
  fill: #3a8dc9;
  opacity: 1;
}
```

To colorize titles of specific folders:
```css
.BookmarkNode[data-type="folder"] > .body[title="Perso"] > .title,
.BookmarkNode[data-type="folder"] > .body[title="Films"] > .title,
.BookmarkNode[data-type="folder"] > .body[title="Presse"] > .title {
  color: #c68317;
}

.BookmarkNode[data-type="folder"] > .body[title="Shopping"] > .title,
.BookmarkNode[data-type="folder"] > .body[title="Temp"] > .title {
  color: #3a8dc9;
}
```
