### DISCUSSION TITLE
How can I change the color of delimiters in the toolbar?

### DISCUSSION THREAD

**Discussion by amadeogarcia** [mbnuqw/sidebery#1831] [Q&A] [answered]
Hello! As the title suggests: is there a way to change the color of delimiters in the toolbar?

[Here](https://imgur.com/TzuMrvZ) is a partial screenshot of my toolbar. The first two horizontal lines are from the sidebar's header, the third horizontal line is a delimiter placed by me.

The delimiter is black by default, meaning it isn't very visible. I looked in the Styles Editor and couldn't find any setting that referred to "delimiter color". I tried a few others like "Toolbar foreground color" and "Button foreground color", but none of them worked.

Hence the question: is this doable? Whether it be from the Styles Editor or from `userChrome.css`.

**Comment by ChilledMoth** [comment, marked as answer]
Try the following rule in the styles editor:

```css
.NavigationBar .nav-item[data-class="space"][data-type="static"]::after {
  background-color: #364259;
}

```
