### DISCUSSION TITLE
Is there any way to hide this section?

### DISCUSSION THREAD

**Discussion by breadone** [mbnuqw/sidebery#1837] [Q&A] [answered]
![Screenshot 2024-10-16 at 09 32 24](https://github.com/user-attachments/assets/1e74f9c1-2282-47fc-b45b-0cee8c3376b8)

I don't switch to the other sidebars at all, that little bit of extra space would be nice

**Comment by ChilledMoth** [comment, marked as answer]
Sure, in a custom userChrome.css file..

```css
@-moz-document url("chrome://browser/content/browser.xhtml") {
  #sidebar-header {
    visibility: collapse;
  }
}
```
