### DISCUSSION TITLE
Allow adding delimiter/seperation bar freely in between tabs?

### DISCUSSION THREAD

**Discussion by MaxHasBeenUsed** [mbnuqw/sidebery#1839] [Ideas]
You can manually add them wherever you want, like in right here. As well as allow dragging to move them or deleting them.

It's supposedly to act like a way to organize tabs by separating them (or grouping them, depends on how you see it.) One level lower than "containers".

![图片](https://github.com/user-attachments/assets/797bad55-92b1-4416-983f-ccae3ee49d2b)

**Comment by ChilledMoth** [comment]
Not sure what you're trying to do, but '.Tab[data-lvl="0"]' gives you the root level tabs..

```css
.Tab[data-lvl="0"] {
  border-top: 1px solid #3F3F46;
}

.Tab[data-lvl="0"]:first-child {
  border-top: unset;
}
```
