### DISCUSSION TITLE
Sidebary sidebar title not hidden after update to Firefox 140 beta

### DISCUSSION THREAD

**Discussion by Dimas-sc** [mbnuqw/sidebery#2144] [Q&A] [answered]
After updating to Firefox 140 beta, the sidebar title "Sidebery" is shown, and it should be hidden by my userChrome.css.

![image](https://github.com/user-attachments/assets/4549208c-946a-4c3e-984f-14d383bf20e4)

This is my userChrome.css working until now:

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

#TabsToolbar {
    visibility: collapse !important;
}

#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"] #sidebar-header {
  display: none;
}
```

The horizontal tabs are hidden, so the file is readed, but I can't hide the sidebar title. Any tips?

Thx

**Comment by ChilledMoth** [comment, marked as answer]
The sidebar header of the legacy sidebar is still being hidden. 

You are using the revamped sidebar (`sidebar.revamp` in `about:config`) to which Mozilla has recently added additional sidebar headers for all web extension sidebar panels ([1943147](https://bugzilla.mozilla.org/show_bug.cgi?id=1943147)).

If you want to continue using it without the headers, try this as your `userChrome.css` file:

```css
@-moz-document url("chrome://browser/content/browser.xhtml") {
  /* hide horizontal tabs toolbar */
  #TabsToolbar {
    visibility: collapse !important;
  }
}

@-moz-document url("chrome://browser/content/webext-panels.xhtml") {
  /* hide revamped sidebar panel header for all web extension sidebar panels */
  sidebar-panel-header {
    display: none !important;
  }
}
```
