### DISCUSSION TITLE
Show hide this part of sidebar

### DISCUSSION THREAD

**Discussion by VinterSolen** [mbnuqw/sidebery#2169] [General]
I *know* i have seen and toggle a setting, somewhere, that toggles between showing and hiding this section. 
But now i have sat for nearly an hour toggling most options that even remotely sounds like it could be that bar/row, but none has hidden it.

Im quite sure its a sideberry setting, much less sure its not a setting for floorp, have not seen a setting for this section "anywhere".

![Screenshot_20250616_114206](https://github.com/user-attachments/assets/d2835637-b32a-4559-bdf2-27b3207fe309)

I am using sideberry on Floorp 12 RC.

**Comment by mbnuqw** [comment]
No, it's the browser part, can be removed with userChrome.css:
```css
#sidebar-header {
  display: none;
}
```

For the new sidebar (sidebar.revamp: true):
```css
#sidebar-panel-header {
  display: none;
}
```
