### DISCUSSION TITLE
Very simple custom CSS to remove the native tabs

### DISCUSSION THREAD

**Discussion by real-felix** [mbnuqw/sidebery#2174] [Show and tell]
Hey, FYI, here is the simplest way to have the tabs removed. Put your tabs as vertical in the settings, and add the following user chrome CSS:

```css
#sidebar-main:not([sidebar-launcher-expanded]), #vertical-tabs {
  visibility: collapse !important;
}
```

It hides entirely the sidebar when it's not expanded, but if you click on the "Expand Sidebar" button, it'll be displayed as usual.
