### DISCUSSION TITLE
Deleting Other Bookmarks and Mobile Bookmarks from list

### DISCUSSION THREAD

**Discussion by ghost** [mbnuqw/sidebery#724] [Q&A]
Is there anyway to get rid, hide or any other option so that other bookmarks and mobile bookmarks doesnt come up on my menu list. Thank you.

**Comment by mbnuqw** [comment]
You can hide them using this CSS in v4:
```css
.bookmarks-wrapper > .Folder:nth-child(3),
.bookmarks-wrapper > .Folder:nth-child(4) {
  display: none;
}
```
and this in v5:
```css
.bookmarks-tree > #bookmarkunfiled_____,
.bookmarks-tree > #bookmarkmobile______ {
  display: none;
}
```
But drag and drop pointer still will be shown at positions of that folders.

Also in v5 (beta) you can create bookmarks panel and set root folder for it. For example, you can create two bookmarks panels for Bookmarks Menu and Bookmarks toolbar.
