### DISCUSSION TITLE
Disabling tab loading animation

### DISCUSSION THREAD

**Discussion by psychoblizzard** [mbnuqw/sidebery#769] [Q&A] [answered]
I've tried setting animations to "off" in the settings menu but cannot seem to disable to spinning blue circle while tabs are loading and the blue swipe when a tab finishes loading. Could you please add in an option to disable these animations as some users might find them distracting. Or is there another way that I am not aware of? Otherwise, awesome extension.

**Comment by mbnuqw** [comment, marked as answer]
Yep, this is planned (in v5). I'll render a static 'hourglass' icon instead of the rotating circle for animationless config.

To disable loading animation right now, you can use this custom CSS (open sidebery settings / styles editor):
For both v5 and v4
```css
.Tab .progress-spinner {
  animation: none !important;
  border: 2px solid green !important;
}
```
