### DISCUSSION TITLE
scroll bar position

### DISCUSSION THREAD

**Discussion by brekco** [mbnuqw/sidebery#790] [Q&A] [answered]
Is it possible to move the scroll bar to the left side of the tabs panel? If so, how?

**Comment by mbnuqw** [comment, marked as answer]
This is possible in current beta version. For the v4 you can use next custom CSS (Sidebery settings / Style editor):
```css
.scroll-container {
  direction: rtl;
}
.scroll-container > .scrollable{
  direction: ltr;
}
```
