### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by devnoot** [mbnuqw/sidebery#1021]
The height in the following CSS (from [Firefox Styles Snippets (via userChrome.css)](https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)) should be changed from `29px` to `40px`. `29px` isn't enough height for the new Firefox tabs.

```css
#main-window #TabsToolbar {
  height: 29px !important;
  overflow: hidden;
  transition: height .3s .3s !important;
}
```
