### ISSUE TITLE
Prevent inactive or collapsed tab favicons from being greyed out

### ISSUE THREAD

**Issue by dnut** [mbnuqw/sidebery#1031]
I would like all favicons to always be displayed with full brightness. I've looked through every setting and messed around with some CSS tweaks, but I can't figure out how to make this happen. I was able to use a CSS tweak to hide the collapsed-branch symbol, but I couldn't figure out how to make the colors look normal.

I use sidebery like an app dock. I have inactive branches configured to automatically collapse. I have sidebery zoomed in significantly, and rely on favicons to decide where to click. At any given moment, most of the icons are very dim, which does not help.

**Comment by mbnuqw** [comment]
You can use this custom CSS
For v4
```css
.Tab {
  --favicons-placeholder-bg: #eee; /* set your color */
}

.Tab[data-parent][data-folded]:not(:hover) .exp {
  display: none;
}
.Tab[data-parent][data-folded]:not(:hover) .fav > img,
.Tab[data-parent][data-folded]:not(:hover) .fav > .placeholder {
  opacity: 1;
}
.Tab[data-discarded] > .lvl-wrapper > .fav {
  opacity: 1;
}
.Tab .fav .child-count {
  right: -6px;
  background-color: var(--bg);
  border-radius: 3px;
  padding: 0 1px;
}
```

For v5:
```css
.Tab[data-parent="true"][data-folded="true"]:not(:hover) .exp {
  display: none;
}
#root .Tab:not(:hover) .body .fav .fav-icon {
  opacity: 1;
}
.Tab[data-discarded="true"] > .body > .fav {
  opacity: 1;
}
.Tab .fav > .child-count {
  right: -6px;
}
```

Also, check #531 and #794

Closing this issue as not planned (for inactive tabs) and as duplicate (for collapsed, #794)

**Comment by dnut** [comment]
Thanks, that works. I made some slight tweaks.

I don't want them to turn grey while hovering, so I removed `:not(:hover)` from the favicon opacity css. There is still one time that icons dim, which is while hovering an expanded tab. Not sure how to get rid of that. But otherwise they're at 100% opacity, which is a satisfying result.

Also I wanted to hide the expansion icon at all times, even when hovering. Removing `:not(:hover)` from your code breaks the button. I used a different approach to hide the icon while still allowing the button to work. 
```css
/* Hides the expansion button angle bracket icon */
#icon_expand {
    display: none;
    visibility: hidden;
}

/* un-greys collapsed branch favicons */
.Tab[data-parent][data-folded] .fav > img,
.Tab[data-parent][data-folded] .fav > .placeholder {
  opacity: 1;
}

/* un-greys discarded tab favicons */
.Tab[data-discarded] > .lvl-wrapper > .fav {
  opacity: 1;
}

/* shifts nested tab counter to the right */
.Tab .fav .child-count {
  right: -6px;
  background-color: var(--bg);
  border-radius: 3px;
  padding: 0 1px;
}
```

**Comment by mbnuqw** [comment]
To not dim icons on hovering over tab, add `.Tab:hover .fav` selector to "un-greys collapsed branch favicons" block:
```css
/* un-greys collapsed branch favicons */
.Tab[data-parent][data-folded] .fav > img,
.Tab[data-parent][data-folded] .fav > .placeholder,
.Tab:hover .fav {
  opacity: 1;
}
```

To not dim icons on hovering over favicon of expanded tab:
```css
.Tab[data-parent] .fav:hover > img,
.Tab[data-parent] .fav:hover > .placeholder {
  opacity: 1;
}
```
