### ISSUE TITLE
Dynamic native tabs

### ISSUE THREAD

**Issue by rauldipeas** [mbnuqw/sidebery#1032]
After the Firefox 103 update, Dynamic native tabs CSS it's not working anymore, how can I fix it?

https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)#dynamic-native-tabs

There's a way to hide the group tabs from the main window (top of the window) to show only tabs inside the current group?

**Comment by mbnuqw** [comment]
Use this CSS (titlepreface is [zero width space](https://unicode-explorer.com/c/200B) `<0x200b>`: "​"):
```css
#main-window #titlebar {
  overflow: hidden;
  transition: height 0.3s 0.3s !important;
}
/* Default state: Set initial height to enable animation */
#main-window #titlebar { height: 3em !important; }
#main-window[uidensity="touch"] #titlebar { height: 3.35em !important; }
#main-window[uidensity="compact"] #titlebar { height: 2.7em !important; }
/* Hidden state: Hide native tabs strip */
#main-window[titlepreface*=""] #titlebar { height: 0 !important; }
/* Hidden state: Fix z-index of active pinned tabs */
#main-window[titlepreface*="​"] #tabbrowser-tabs { z-index: 0 !important; }
```

**Comment by mbnuqw** [comment]
Fixed the snippet in wiki

**Comment by rauldipeas** [comment]
Thanks! It's worked like a charm!

And about my second question? Any way to do so?

**Comment by mbnuqw** [comment]
Oh, sorry, didn't notice. Yes, but only in beta version and only for folded groups: Sidebery setting / Tabs / Tabs Tree / "Hide folded tabs" and "Hide parent tab: group tab".

**Comment by rauldipeas** [comment]
Thanks! I switched to the beta and set as You guided-me, great workflow now!

**Comment by arjpar** [comment]
@mbnuqw The horizontal tabs are hiding upon open of the sideberry sidetab, but when I close the sideberry side tab the horizontal tabs don't appear again.

**Comment by mbnuqw** [comment]
@arjpar, what version of Sidebery and Firefox?

**Comment by arjpar** [comment]
> @arjpar, what version of Sidebery and Firefox?

@mbnuqw I'm using the latest version of Sideberry beta (v5.0.0rc4) and Firefox v117.0 on macOS.

**Comment by mbnuqw** [comment]
@arjpar, Can't reproduce this, check if you use some other addon that changes/handles window's title.

**Comment by arjpar** [comment]
@mbnuqw I did some debugging and the preface value doesn't go away when I close the sidebery sidebar. When I open the sidebery sidebar, the preface value only goes away for a brief few milliseconds and then appears again.

Edit: Figured it out. Seemed to be a problem with firefox-ui-fix (lepton).

**Comment by merof-code** [comment]
> Use this CSS (titlepreface is [zero width space](https://unicode-explorer.com/c/200B) `<0x200b>`: "​"):
> 
> ```css
> #main-window #titlebar {
>   overflow: hidden;
>   transition: height 0.3s 0.3s !important;
> }
> /* Default state: Set initial height to enable animation */
> #main-window #titlebar { height: 3em !important; }
> #main-window[uidensity="touch"] #titlebar { height: 3.35em !important; }
> #main-window[uidensity="compact"] #titlebar { height: 2.7em !important; }
> /* Hidden state: Hide native tabs strip */
> #main-window[titlepreface*=""] #titlebar { height: 0 !important; }
> /* Hidden state: Fix z-index of active pinned tabs */
> #main-window[titlepreface*="​"] #tabbrowser-tabs { z-index: 0 !important; }
> ```

I've tried the current wiki, tried this piece of code, it did not work.


Also tried:
This is Firefox 127.0.2
I created a new empty default profile. Added sidebery, enabled `toolkit.legacyUserProfileCustomizations.stylesheets`, created `chrome/userChrome.css` file with contents as follows
```css
#main-window #titlebar {
  overflow: hidden;
  transition: height 0.3s 0.3s !important;
}
/* Default state: Set initial height to enable animation */
#main-window #titlebar { height: 3em !important; }
#main-window[uidensity="touch"] #titlebar { height: 3.35em !important; }
#main-window[uidensity="compact"] #titlebar { height: 2.7em !important; }
/* Hidden state: Hide native tabs strip */
#main-window[titlepreface*="XXX"] #titlebar { height: 0 !important; }
/* Hidden state: Fix z-index of active pinned tabs */
#main-window[titlepreface*="XXX"] #tabbrowser-tabs { z-index: 0 !important; }
```

and it did not work. When removed `[titlepreface*="XXX"]`, the tabs disappeared as expected.
