### ISSUE TITLE
[Idea] Floating button to scroll to active tab

### ISSUE THREAD

**Issue by emvaized** [mbnuqw/sidebery#1133]
## Description
Arc browser recently introduced a new feature — when active tab gets scrolled out of the viewport, small floating button appears on the corresponding side, which allows to scroll panel back to the active tab on click: 
![unnamed](https://github.com/mbnuqw/sidebery/assets/37851576/ea2ce69d-9f73-46a3-bb6d-1f3b87839898)

I think it might be a great idea, worthy to be added some day to Sidebery. 

I can even think about slightly enhanced implementation — instead of just an arrow button, show the active tab itself (e.g. make it sticky on scroll); on click it may either scroll the panel back to the tab, or perform configured tab click action (or do both).

**Comment by SunnyZebra** [comment]
Had a similar idea. Fortunately you can use all css styles.

For now that seems to work for me in Sidebery [v5.0.0rc4]

Example to let tab stick just a bit out from top/bottom
```css
.Tab[data-active="true"] {
	position: sticky !important;
	top: calc( 8px - var(--tabs-height));
        bottom:calc( 8px - var(--tabs-height));
}
```

or stick tab at top/bottom so that full tab is shown

```css
.Tab[data-active="true"] {
	position: sticky !important;
	top: 0;
        bottom: 0;
}
```

maybe need to add an additional background-color without alpha to `.Tab[data-active="true"] .body {}`  if it is currently transparent
