### ISSUE TITLE
Numbered tabs

### ISSUE THREAD

**Issue by nollinvoyd** [mbnuqw/sidebery#119]
I'm brand new to Sidebery.  Very interesting.

I have numbered tab in my tab bar.  Accomplished by an userchrome.css entry.

If not actually adding it as a "feature", could someone suggest how to do it with css?

**Comment by mbnuqw** [comment]
You can try to put this css to css editor (in settings / styles editor):
```css
/* globally */
/*
#root {
  counter-reset: tabs;
}
.Tab:nth-of-type(n + 1) {
  counter-increment: tabs;
}
*/

/* per-panel */
.panel {
  counter-reset: tabs;
}
.Tab:nth-of-type(n + 1) {
  counter-increment: tabs;
}

/* num style */
.Tab:nth-of-type(n):before {
  content: counter(tabs);
  position: relative;
  padding: 0 0 0 3px;
  color: #787878;
  font: 11px sans-serif;
}

/* fix margin */
.Tab .fav {
  margin-left: 3px;
}
```
![screenshot-2020-01-08 22:54:06](https://user-images.githubusercontent.com/6276694/72002770-df728280-3269-11ea-92ee-a81b71230b9b.png)

But this will skip folded tabs, so maybe it is not very useful sorry.
