### ISSUE TITLE
Prepend identifier symbols before folded/expanded tabs

### ISSUE THREAD

**Issue by drkhn1234** [mbnuqw/sidebery#1224]
- ### Prepend identifier symbols before folded/expanded tabs

## Description

For example: Say, Tab A is parent tab of a branch with the title "Hello", and if it's: 

-folded
Rename title to: "> Hello"

-expanded
Rename title to: "^ Hello"

#### My usecase is that I changed from settings for Sidebery to "Hide native tabs inside folded branch", which declutter Ctrl+Tab recents switcher of Firefox. Now, it would help me to recognize whether a tab is of the type parent of a branch if its title could be renamed by Sidebery to include an identifier symbol at its beginning similar to examples given above.

**Comment by mbnuqw** [comment]
If you're talking about titles of native tabs, it's most likely won't be implemented because to do this sidebery needs to inject scripts to all parent tabs and change their document.title. It should also handle title change made by the page itself. This also won't work with some internal and unloaded pages.

If we are talking about sidebery tabs, then the desired result can be achieved by using custom CSS:
```css
.Tab[data-parent="true"][data-folded="true"] .t-box .title:before {
  content: '> ';
}

.Tab[data-parent="true"][data-folded="false"] .t-box .title:before {
  content: '^ ';
}
```
