### ISSUE TITLE
Dynamic sidebar userChrome.css doesn't work in FF 72

### ISSUE THREAD

**Issue by snowe2010** [mbnuqw/sidebery#124]
## Steps to reproduce

upgrade to FF 72, attempt to use the Dynamic Sidebar code from the readme. 

## Expected behavior

Hovering over the sidebar should cause it to expand

## Actual behavior

It does not expand

## Environment info

OS:  MacOS Mojave
Firefox version: 72.0.1 
Addon version: 4.2.0

**Comment by mbnuqw** [comment]
Yes, looks like this hack doesn't work anymore. You can try this css:
```css
:root {
  --sidebar-min-width: 33px;
  --sidebar-visible-width: 300px;
}

#sidebar-header {
  overflow: hidden !important;
}

#sidebar-box #sidebar-header {
  display: none !important;
}

#sidebar,
#sidebar-header {
  position: relative !important;
  min-width: var(--sidebar-min-width) !important;
  max-width: var(--sidebar-min-width) !important;
  transition: .2s ease .25s;
  z-index:1;
}

#sidebar-box:hover :-moz-any(#sidebar,#sidebar-header) {
  background-color: var(--toolbar-bgcolor) !important;
  min-width: var(--sidebar-visible-width) !important;
  max-width: var(--sidebar-visible-width) !important;
  margin-right: calc((var(--sidebar-visible-width) - var(--sidebar-min-width)) * -1) !important;
  z-index:1;
  position: relative !important;
  transition: .2s ease .25s;
}
```
From this post: https://www.reddit.com/r/FirefoxCSS/comments/ep8r6j/side_tabs_on_hover_using_sidebery_addon/
