### ISSUE TITLE
Change opacity of unloaded tabs (don't dim)

### ISSUE THREAD

**Issue by OrionFOTL** [mbnuqw/sidebery#1251]
There used to be a way to change the opacity of unloaded tabs, so they're not dimmed, but the CSS selectors I used aren't there anymore after updating to v5.0.

Unloaded tabs being dimmed by default:
![obraz](https://github.com/mbnuqw/sidebery/assets/8158804/1013698f-10db-4cd0-ba6c-014fbaa336fe)

What I used before to change their opacity to 1:
```
.Tab[data-discarded] .lvl-wrapper {
    opacity: 1;
}
.Tab[data-discarded] > .lvl-wrapper > .fav,
.Tab[data-discarded] > .lvl-wrapper > .t-box {
    opacity: 1;
}
```

There's no `.lvl-wrapper` class anymore, so I'm not sure which selectors to use to change their opacity. (Or whatever is used to make them dimmer, in case it's not opacity anymore)

**Comment by mbnuqw** [comment]
`.lvl-wrapper` >> `.body`
`data-discarded` >> `data-discarded="true"`
```css
.Tab[data-discarded="true"] .body {
    opacity: 1;
}
.Tab[data-discarded="true"] > .body > .fav,
.Tab[data-discarded="true"] > .body > .t-box {
    opacity: 1;
}
```
