### ISSUE TITLE
Put pinned tabs above navigation bar

### ISSUE THREAD

**Issue by Akryum** [mbnuqw/sidebery#1253]
## Description

Have the option to put pinned tabs above the navigation bar (where usually there are the panes). This would allow to better represent that pinned tabs are global to the panes.

For example:

 Before:

![image](https://github.com/mbnuqw/sidebery/assets/2798204/d5d83940-d736-4e91-b823-7a8ccf9348be)

After:

![image](https://github.com/mbnuqw/sidebery/assets/2798204/ee8a6494-ad55-49a8-b38c-4244c62849d4)

**Comment by real-felix** [comment]
I cannot access the HTML, and I never used vue, but this is the bar's class: `.PinnedTabsBar`.

Trying changing the order only does some weird thing:

```css
.PinnedTabsBar {
  order: 1;
}
```

EDIT: I could debug the HTML, with this link: `moz-extension://<extension URL>/sidebar/sidebar.html`.

Unfortunately, for some reason, the groups tab is one block with class `top-horizontal-box` while the pinned tabs are within the big box with class `main-box`. So it's not trivial to make this change (at least for me). I wonder what was the reason for doing that, instead of having a flat structure.

**Comment by real-felix** [comment]
OK, I did it:

```css
.PinnedTabsBar {
  position: fixed;
  top: 0;
  left: 0;
}

.top-horizontal-box {
  margin-top: var(--tabs-pinned-height);
}
```

It's crappy and brittle (may break in a further update), but it does the job currently.

Note that it won't work if you have your pinned tabs on several lines. If you have 2 lines, the margin must be `calc(2 * var(--tabs-pinned-height))`, etc.
