### ISSUE TITLE
Question: Container indicator colors position to left side

### ISSUE THREAD

**Issue by K-no-Uta** [mbnuqw/sidebery#1259]
Hello. I just got an update and  ..... I'm not entirely sure to be honest but I feel like container indicator color lines jumped to the right side of the sidebar?? They are really hard to see and I need these colors to be on the left side before the tab names. 

If anyone can give me a hint on the option or section or adjustment that can get this changed??
I did see that you can dye the whole name in the container color, but that affect readability too much + is visially busy and that doesn't bode well with my brain!

Please be VERY detailed. I may have to stranslate stuff So if it's an existing option please give me the exact section within the options. If I have to put in some sort of command somewhere, please be very detailed where and how. I'm a bit of a rookie when it comes to such stuff!

Thank you.

**Comment by mbnuqw** [comment]
Use this custom CSS:
```css
#root .Tab[data-pin="false"] .ctx {
  right: auto;
  left: 0;
  top: 0;
  height: 100%;
  border-top-left-radius: 2px;
  border-bottom-left-radius: 2px;
}
```
Open `Sidebery settings >> Styles editor` and paste these CSS styles into the text field (the right column)
