### ISSUE TITLE
Rearrange bottom bar? 

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [mbnuqw/sidebery#1322]
## Description
Any way to rearrange the bottom bar so it's in the order: "History - Recently closed - Bookmarks"? It's more intuitive and resembles the native firefox menu order. Maybe using CSS?

**Comment by mbnuqw** [comment]
Custom style workaround:
```css
.BottomBar > .tool-btn:nth-child(3) {
  order: 1;
}
.BottomBar > .tool-btn:nth-child(1) {
  order: 2;
}
.BottomBar > .tool-btn:nth-child(2) {
  order: 3;
}
```
