### ISSUE TITLE
Colorize tabs only when mouse is in the sidebar

### ISSUE THREAD

**Issue by SmurgBurglar** [mbnuqw/sidebery#1334]
It would be nice to have the option that tabs would only colorize when the mouse was in the sidebar to preserve the browser theme.

**Comment by SunnyZebra** [comment]
Not sure if it sets background for every case but should work for most cases.

Just have to insert into the custom sidebery styles.

Color on tab hover
```css
.Tab .color-layer {
  background-color: transparent;
}

.Tab:hover .color-layer {
  background-color: var(--tab-color);
}
```

or if you want to have fading mixed colors instead of simple transparent background a mix of tab color and transparent background

```css
.Tab .color-layer {
  background-color: color-mix(in srgb, var(--tab-color) 20%, transparent);
}

.Tab:hover .color-layer {
  background-color: var(--tab-color);
}
```

or how you described color when mouse hovers over sidebar
```css
.Tab .color-layer {
  background-color: color-mix(in srgb, var(--tab-color) 20%, transparent);
}

.main-box:hover .Tab .color-layer {
  background-color: var(--tab-color);
}
```

**Comment by mbnuqw** [comment]
Closing this as it has workaround (third option in @SunnyZebra's comment) or if you want to completely reset colorization styles in default state:
```css
#root.root .Tab[data-colorized="true"] {
  --tabs-activated-shadow: var(--active-el-shadow);
}
.Tab .color-layer {
  display: none;
}

.main-box:hover .Tab .color-layer {
  display: block;
}
#root[data-frame-color-scheme="dark"] .main-box:hover .Tab[data-colorized="true"] {
  --tabs-activated-shadow: inset 0 0 0 1px #fff7,
                           0 1px 3px -1px #00000036;
}
#root[data-frame-color-scheme="light"] .main-box:hover .Tab[data-colorized="true"] {
  --tabs-activated-shadow: inset 0 0 0 1px #0009,
                           0 1px 3px -1px #00000032;
}
```
