### ISSUE TITLE
[Feature request] Dynamic `--tabs-indent` value based on max tree depth

### ISSUE THREAD

**Issue by Lej77** [mbnuqw/sidebery#1339]
## Description

Tree Style Tab has this feature where if you have a very nested tree structure then the tab indent is lowered inside that window. This even respects hidden/collapsed tabs so when those deeper trees aren't visible you can use the larger tab indents.

I made the following custom CSS style to mimic such behavior:
<details>
  <summary>Custom CSS Style</summary>
  
```css
/* Dynamic tree indentation ("--tabs-indent" is no longer a constant): */
@supports selector(:has(*)) {
    #root {
        /* Don't use more than this part of the sidebar's horizontal space for
        * indentation. To only use 50% of sidebar's horizontal space set this to
        * "0.5". To remove the limit set this to "1":
        */
        --max-part-of-sidebar: 0.4;
        /* Don't indent a tab more than this when its a child of a root node, so
        * this is the max horizontal distance between a parent and child tab.
        */
        --max-tab-indent-per-level: 16px;

        /* Max total width that is used for tree indentation. */
        --max-total-indent: calc(calc(100vw * var(--max-part-of-sidebar)));
    }
    .TabsPanel {
        --tree-depth: 16;
        /* Round to whole pixels otherwise the "Show marks to indicate tabs sub-tree levels" will have graphical glitches. */
        --tabs-indent: round(calc(min(var(--max-total-indent) / var(--tree-depth), var(--max-tab-indent-per-level))), 1px);
    }
    /* Find the deepest tree depth, the rules prefer smaller depths because of their ordering: */
    .TabsPanel:not(:has(.Tab[data-lvl="16"])) {
        --tree-depth: 15;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="15"])) {
        --tree-depth: 14;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="14"])) {
        --tree-depth: 13;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="13"])) {
        --tree-depth: 12;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="12"])) {
        --tree-depth: 11;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="11"])) {
        --tree-depth: 10;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="10"])) {
        --tree-depth: 9;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="9"])) {
        --tree-depth: 8;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="8"])) {
        --tree-depth: 7;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="7"])) {
        --tree-depth: 6;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="6"])) {
        --tree-depth: 5;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="5"])) {
        --tree-depth: 4;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="4"])) {
        --tree-depth: 3;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="3"])) {
        --tree-depth: 2;
    }
    .TabsPanel:not(:has(.Tab[data-lvl="2"])) {
        /* Only root tabs and their children. */
        --tree-depth: 1;
    }
}
```

</details>

The custom style makes use of the new [`:has()`](https://developer.mozilla.org/docs/Web/CSS/:has) CSS selector to determine the max tree depth. That selector [isn't stable on Firefox yet](https://connect.mozilla.org/t5/ideas/when-is-has-css-selector-going-to-be-fully-implemented-in/idc-p/23811/highlight/true#M19085) but it is [available in nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=418039#c78). I [enabled it via `about:config` though using the `layout.css.has-selector.enabled` setting](https://stackoverflow.com/questions/73936048/how-do-you-enable-has-selector-on-firefox) and it seems to work correctly.

Anyway I thought it might make sense to implement something like this inside Sidebery itself. Then the `:has()` selector wouldn't be needed since you could use JavaScript to set an attribute to the `.TabsPanel` that indicated the max visible tree depth. (And use that in the CSS rules instead.)

I imagine this would be controlled using a `--max-total-indent` CSS variable in the `Styles editor` that could be set to `100vw` to get the previous behavior (a constant `--tabs-indent` variable that doesn't care about max tree depth). (Well so long as you never had trees that were completely outside the sidebar, that seems completely unusable though so I don't think anyone depends on that behavior.)
