### ISSUE TITLE
[Feature Request] Add "Recently closed tabs" as a panel in Navigation bar

### ISSUE THREAD

**Issue by KiKaraage** [mbnuqw/sidebery#1465]
## Description

Basically as stated in title. 

(I'm building a theme to mimic Arc in Firefox, involving Sidebery. Would love to have Recently closed tabs as a panel option in Sidebery navigation bar.)
![gambar](https://github.com/mbnuqw/sidebery/assets/10529881/e7e61d86-d575-4d22-bbc6-b76322e4f7dc)

**Comment by KiKaraage** [comment]
Additional question: I'd like to know how to replace the default icons from the CSS Style Editor, like the history icon or new tab panel icon for example

![gambar](https://github.com/mbnuqw/sidebery/assets/10529881/a88ce093-7cd9-400c-8310-1df3bfbd1e50)
_reference: Arc Browser Spaces_

**Comment by mbnuqw** [comment]
You can set fill to transparent to hide standard icon, set background-color to desired color and use desired icon as mask:
```css
.NavigationBar #navhistory.nav-item .icon {
  fill: transparent;
  background-color: red;
  mask: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAApUlEQVQ4T2NkoBAwUqifgZABB4AW/AdiR1wW4TOgAaipHqoRxG7EZgguA5A1w/SBDACJowBcBnwAquJHUwsSEyTWAJC/iXIxNhcYAHWex2GAIVD8ArIcNgOw+R9nOKAbkABUOR9XlEHFE4H0ApgaZAMUgIL3CWgGSX8EYgFsBhChF1MJvoS0AajcH6plI5AOICpakBQhhweKvwnFAkleIZSZCBoGAP8NFRHd8RknAAAAAElFTkSuQmCC");
}
```
