### ISSUE TITLE
Audio Badge covering Tabs Button

### ISSUE THREAD

**Issue by soulhotel** [mbnuqw/sidebery#1466]
Is there a way to remove this audio badge (the button with the mute/unmute ALL function).

I tried using the debugger in the panel configuration but I'm having trouble identifying what it is and how to edit it.

![Screenshot_1](https://github.com/mbnuqw/sidebery/assets/155501797/75e2bb59-c7d2-4fc5-bfb8-e768347e8183)

**Comment by mbnuqw** [comment]
```css
.NavigationBar .nav-item .audio {
  display: none;
}
```
