### ISSUE TITLE
Dynamic multiline titles

### ISSUE THREAD

**Issue by shimeoki** [mbnuqw/sidebery#1471]
I tried the code snippet from [here](https://github.com/mbnuqw/sidebery/wiki/Sidebery-Styles-Snippets#tabs-multiline-titles), but it makes multiline constant on all tabs. So if you want more than two lines, every other tab with less content looks very awkward. And if you set it to 2 lines, all other lines will be hidden. For example, the Tree Style Tab extension does [this](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#wrap-tab-titles-instead-of-cropping-2929):
![image](https://github.com/mbnuqw/sidebery/assets/79855381/41626259-654e-402d-912e-356aec3c20de)
according to the content wrap, the height of the tabs changes dynamically. I really like your extension because of all of the other features and implementing this will be wonderful.

Also, while I was inspecting CSS, I found this:
![firefox_UDq2TuVqIO](https://github.com/mbnuqw/sidebery/assets/79855381/aae29be2-2532-4678-9fd5-13c474564650)
Firefox thinks this line of code in the snippet does nothing because the t-box is not a flex container.

**Comment by SunnyZebra** [comment]
Got me thinking. Seems possible. With the following css changes ~~seems to work for me.~~ it is visually correct, but sidebery code needs to be adjusted to get correct drag and drop tab position for dynamic tab heights.

Some additional changes to the 2-line example

not a copy paste example. Just quickly tested which css values needs to be changed

```css
/* add inside .tab { }*/
.tab{
height:auto;
}

/* can be removed seems superflous */
.Tab .t-box {
/* 
  max-height: calc(var(--tabs-height) - var(--tabs-title-padding));
  overflow: hidden;
*/
}

/* remove line-height from .tab .title()
*/ 
.Tab .title {
 white-space: pre-wrap; /* still needed */
/*
  line-height: calc(
    (var(--tabs-height) - var(--tabs-title-padding)) / var(--tabs-title-lines)
  );
*/
  -webkit-line-clamp: var(--tabs-title-lines); /* important line to clamp to max lines*/
}

in root{} change --tabs-title-lines: 2; to desired max tab lines

```

short comment if it's working for other multiline users and i have not forgotten any other css line to mention.

Edit:
Just reworked it on an empty custom css.  ~~The following is the minimum needed css code to have nice dynamic multilines.~~
```css
#root {
  --tabs-height: 36px;
  --tabs-title-lines: 3;
}

.Tab{
  height:auto;
}

.Tab .t-box{	
  min-height: calc(var(--tabs-height));

  display:flex;
  align-items:center;
}

.Tab .title {
  font-size: var(--tabs-font-size);
  white-space: pre-wrap;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: var(--tabs-title-lines);
}
```

**Comment by shimeoki** [comment]
> Got me thinking. Seems possible. With the following css changes seems to work for me. Some additional changes to the 2-line example
> 
> not a copy paste example. Just quickly tested which css values needs to be changed
> 
> ```css
> /* add inside .tab { }*/
> .tab{
> height:auto;
> }
> 
> /* can be removed seems superflous */
> .Tab .t-box {
> /* 
>   max-height: calc(var(--tabs-height) - var(--tabs-title-padding));
>   overflow: hidden;
> */
> }
> 
> /* remove line-height from .tab .title()
> */ 
> .Tab .title {
>  white-space: pre-wrap; /* still needed */
> /*
>   line-height: calc(
>     (var(--tabs-height) - var(--tabs-title-padding)) / var(--tabs-title-lines)
>   );
> */
>   -webkit-line-clamp: var(--tabs-title-lines); /* important line to clamp to max lines*/
> }
> 
> in root{} change --tabs-title-lines: 2; to desired max tab lines
> ```
> 
> short comment if it's working for other multiline users and i have not forgotten any other css line to mention.
> 
> Edit: Just reworked it on an empty custom css. The following is the minimum needed css code to have nice dynamic multilines.
> 
> ```css
> #root {
>   --tabs-height: 36px;
>   --tabs-title-lines: 3;
> }
> 
> .Tab{
>   height:auto;
> }
> 
> .Tab .t-box{	
>   min-height: calc(var(--tabs-height));
> 
>   display:flex;
>   align-items:center;
> }
> 
> .Tab .title {
>   font-size: var(--tabs-font-size);
>   white-space: pre-wrap;
>   display: -webkit-box;
>   -webkit-box-orient: vertical;
>   -webkit-line-clamp: var(--tabs-title-lines);
> }
> ```

Wonderful idea, thank you! But there is one big problem.

But first I tweaked the config a bit for myself, as I wanted it to be scalable with font size and more white space.
```css
#root {
	--tabs-min-height: calc(3 * var(--tabs-font-size));
	--tabs-max-title-lines: 10;
	--tabs-vertical-padding: 6px;
	--tabs-title-spacing: 4px;
	--tabs-font-size: 0.875rem;
}

.Tab {
	height: auto;
}

.Tab .t-box {	
	min-height: var(--tabs-min-height);
	display: flex;
	align-items: center;
	padding: var(--tabs-vertical-padding) 0px;
}

.Tab .title {
	white-space: pre-wrap;
	display: -webkit-box;
	-webkit-box-orient: vertical;
	-webkit-line-clamp: var(--tabs-max-title-lines);
	line-height: calc(var(--tabs-font-size) + var(--tabs-title-spacing));
}
```

So the problem is that dragging tabs does not work properly. As I've tested, it calculates hitbox for dragging with `--tabs-height` variable. So, if height is dynamic with `-webkit-line-clamp`, I don't know how with only CSS we can get current title lines count for changing it.

Example: 
![image](https://github.com/mbnuqw/sidebery/assets/79855381/63fb6650-c5cb-472f-8dbc-57c0291ddead)
Expected behaviour: Tab is between two GitHub tabs. Result: Nothing happens, because the real hitbox is smaller.

If I set `--tabs-height` to 100px, for example, here is what happens:
![image](https://github.com/mbnuqw/sidebery/assets/79855381/288418ac-1b1f-41c1-9d31-14225c90f73d)
The separator is located under all tabs.

Also, the "X" close button for tabs scales with the height of the tab, so it looks very strange with only 3 lines, not saying for more.
