### ISSUE TITLE
Make minimum panel size user-selectable

### ISSUE THREAD

**Issue by notorand-it** [mbnuqw/sidebery#1529]
## Description
I would like to be bale to reduce the side panel without any minimum when I am not on my 28" screen.
I cannot go less than a certain amount.
Vivaldi browser (chromium based) has this feature.
At least make the minimum size configurable.

**Comment by mbnuqw** [comment]
It's impossible to do from addon side. It's Firefox restrictions (idk why) that can be changed only with [userChrome.css hacks](https://www.reddit.com/r/FirefoxCSS/wiki/index/tutorials)
Example:
```css
#sidebar-box #sidebar-header {
  overflow: hidden !important;
}
#sidebar-box,
#sidebar-box #sidebar {
  min-width: 30px !important;
  max-width: auto !important;
}
```
