### ISSUE TITLE
Feature request: automatic unloading of old tabs

### ISSUE THREAD

**Issue by MMachado05** [mbnuqw/sidebery#1586]
### Description

I'm not sure if this is beyond the scope of what this project intends to accomplish, but considering how feature-rich it's already become, I figure this might be a welcome addition. The Auto-Discard Tabs extension for FF is just over a year out of date, and any recent commits on its repo are only relevant to the Chrome version of the extension. I feel like including an option to automatically unload tabs might be very helpful, and seems to be in line with the kinds of productivity improvements Sidebery wants to offer.

**Comment by MMachado05** [comment]
Relatedly, an replacing the favicon for unloaded tabs with something "showing" that the tab is unloaded (akin to how ATD replaces them with the 💤 emoji) could be beneficial in quickly displaying what tabs are unloaded when Sidebery isn't open!

**Comment by mbnuqw** [comment]
Duplicate of #598

For "💤" favicon, use this custom style (Sidebery settings > Styles editor):
```css
#root .Tab[data-discarded="true"] .fav > .fav-icon {
  opacity: 0;
}
#root .Tab[data-discarded="true"] .fav {
  opacity: 1;
}
.Tab[data-discarded="true"] .fav:before {
  content: '💤';
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  font-size: 1rem;
  line-height: 16px;
  text-align: center;
}
```
