### ISSUE TITLE
Feature request: add option to continuously highlight tabs that play sound

### ISSUE THREAD

**Issue by hansdampfinger666** [mbnuqw/sidebery#1669]
### Description

If I have a large amount of media tabs open (like Youtube) it's really hard to see which one is currently playing something (audio/video), when I'm not on it currently. 
It'd be really cool to have an option to highlight that audible tab somehow, so I can find it quickly again.

**Comment by SunnyZebra** [comment]
Haven't seen an option, but custom stylesheets is your friend.

I pulsate border color and audio icon when audio of a tab is playing.
You can find inspiration from my code and adjust to your liking and use it in the styles editor.

```css
#root.root{ 
 --long-transition-time: 1.4s;
}

@keyframes borderSoundPlaying {
  0%,
  100% {
    border: 2px green groove;
    background-color: rgba(0, 0, 0, 0.2);
  }

  50% {
    border: 2px blue groove;
    background-color: rgba(0, 0, 0, 1);
  }
}

@keyframes audio-animation {
  0%,
  100% {
    scale: 1;
    fill: white;
  }
  50% {
    scale: 1.4;
    fill: rgba(250, 50, 50, 0.8); 
  }
}

.Tab[data-audible="true"] .body {
  animation: borderSoundPlaying var(--long-transition-time) linear infinite;
}
.Tab[data-audible="true"] .audio > svg {
  border: 0 !important;
  animation: audio-animation var(--long-transition-time) linear infinite;
}
```

**Comment by hansdampfinger666** [comment]
I'd prefer a constant outline/highlight, so I just cranked the transition time up to 100 and that works just fine (and I have no clue of web tech/JS etc.). Thanks @SunnyZebra!

**Comment by SunnyZebra** [comment]
Then you need even less code. 
Just having a static border around tabs with playing media this part is enough.

```css
.Tab[data-audible="true"] .body {
      border: 2px green groove;
}
```
