### ISSUE TITLE
Reduce the minimum width of Sidebery.

### ISSUE THREAD

**Issue by mowanotm** [mbnuqw/sidebery#1672]
### Description

In order to protect from fingerprinting user's screen resolution, Firefox privacy.resistFingerprinting.letterboxing limits the rendering size of web page to some common rounded values and report as user screen resolution.
For example, a 1920x1080 screen minus the height of windows taskbar and firefox tabs, could achieve a rounded letterbox of 1800x900 for web page rendering. Since Sidebery occupy a minimum of 168px width, the next best rounded letterbox a Sidebery user can achieve is 1600x900. 
If the minimum width of Sidebery is reduced, Sidebery users, who opt for privacy.resistFingerprinting.letterboxing, might have the option to achieve a larger letterbox.

**Comment by alexiscent** [comment]
Don't know if anything has changed since [this](https://github.com/mbnuqw/sidebery/issues/1234#issuecomment-1725949053) reply, but it's still easy to do with userChrome. Here's mine as an example:
```css
:root {
  --sidebar-min-width: 30px;
  --sidebar-visible-width: 230px;
}

#sidebar-box, #sidebar{
  position: relative !important;
  min-width: var(--sidebar-min-width) !important;
  max-width: var(--sidebar-min-width) !important;
  transition: .1s ease .3s;
  z-index: 1;
}

#sidebar-box:hover #sidebar {
  min-width: var(--sidebar-visible-width) !important;
  max-width: var(--sidebar-visible-width) !important;
  transition: .1s ease .2s;
}

#sidebar-header { display: none; }
#sidebar-splitter { display: none; }
#webextpanels-window { background: transparent !important }
```
