### ISSUE TITLE
Ability to toggle a horisontal panel tab bar

### ISSUE THREAD

**Issue by dxlr8r** [mbnuqw/sidebery#1795]
### Description

Usually I prefer a vertical tab bar. But sometimes, to save space, it would be great to be able toggle a horisontal bar containing the tabs in a specific panel.

The main difference here between the Firefox built in horisontal bar, and this feature, is the panel scoping. Firefox does not have a concept of panels, and shows all tabs, from all panels. Which would result in to many tabs being present in the bar.

**Comment by albino1** [comment]
Take a look at:

`Settings` -> `Tabs` -> `Native (horizontal) tabs`

I currently have both Sidebery and default firefox tabs and it only shows the ones in my current Sidebery panel with `Hide native tabs of inactive panels` enabled.

**Comment by dxlr8r** [comment]
Thank you, that worked.

Also tweaked userChrome.css. I found setting `display` better than height, as I then could just target `#TabsToolbar`, so that I can still get view the menu bar when I press "alt" without glitches.

```css
#sidebar-header {
  display: none;
}

#main-window #TabsToolbar { display: inherit; }
#main-window[uidensity="touch"] #TabsToolbar { display: inherit; }
#main-window[uidensity="compact"] #TabsToolbar { display: inherit; }
/* Hidden state: Hide native tabs strip */
#main-window[titlepreface*="🦊"] #TabsToolbar { display: none; }
/* Hidden state: Fix z-index of active pinned tabs */
#main-window[titlepreface*="🦊"] #tabbrowser-tabs { z-index: 0 !important; }
```
