### ISSUE TITLE
Sidebar always collapsed

### ISSUE THREAD

**Issue by Andr3wcr0z** [mbnuqw/sidebery#1886]
### Steps to reproduce

- Open Firefox in a new profile
- Install Sidebery
- Open Sidebery
- Hover over the sidebar

### Actual behavior

until today when firefox updated, my sidebery was working just fine but now it's not opening it's collapsed no matter whether my cursor is hovered or clicking or none of the above.
This is what it looks like when being hovered over:
<img width="184" alt="Screenshot 2024-11-26 at 8 19 53 AM" src="https://github.com/user-attachments/assets/49207073-b3d1-4a2d-9487-cdfff1e66c72">

### Expected behavior

The sidebar should open flawlessly

### System

14.2.1

### Firefox version

133.0

### Sidebery version

1.6.6

### Logs

```code
[bg] Init start chunk-4KZVVU6Z.js:2:7890
[sidebar] Init start chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Sidebar.loadPanels chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Sidebar.loadPanels: Done: 19ms chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Tabs.load chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Tabs.restoreTabsState chunk-4KZVVU6Z.js:2:7890
[bg] Init end: 667ms chunk-4KZVVU6Z.js:2:7890
[bg] IPC.onConnected sidebar 3 chunk-4KZVVU6Z.js:2:7890
[bg] Windows.isWindowTabsLocked 3 chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Tabs.findCachedData: mismatched: 1 1 5 chunk-4KZVVU6Z.js:2:7976
[sidebar:3] Tabs.restoreTabsFromSessionData chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Tabs loading: Cannot find panels: -1 chunk-4KZVVU6Z.js:2:7976
[sidebar:3] Tabs.restoreTabsState: Done: 17ms chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Tabs.load: Done: 23ms chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Init end: 658ms chunk-4KZVVU6Z.js:2:7890
[bg] IPC.onDisconnected sidebar 3 chunk-4KZVVU6Z.js:2:7890
[sidebar] Init start chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Sidebar.loadPanels chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Sidebar.loadPanels: Done: 4ms chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Tabs.load chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Tabs.restoreTabsState chunk-4KZVVU6Z.js:2:7890
[bg] IPC.onConnected sidebar 3 chunk-4KZVVU6Z.js:2:7890
[bg] Windows.isWindowTabsLocked 3 chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Tabs.findCachedData: mismatched: 2 7 7 chunk-4KZVVU6Z.js:2:7976
[sidebar:3] Tabs.restoreTabsFromSessionData chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Tabs.restoreTabsState: Done: 6ms chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Tabs.load: Done: 19ms chunk-4KZVVU6Z.js:2:7890
[sidebar:3] Init end: 55ms
```

**Comment by Obiswaggylordie** [comment]
I've discovered that this is mainly caused by some issue in the userchrome file typically, I've solved it on my end by replacing my sidebery hiding code with this one:
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_sidebar.css

**Comment by ZorisBube** [comment]
> I've discovered that this is mainly caused by some issue in the userchrome file typically, I've solved it on my end by replacing my sidebery hiding code with this one: https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_sidebar.css

Thank you Obiswaggylordie... This one solved my issue, too!

**Comment by santinoscripts** [comment]
Anyone knows how can I fix this code so it works with FF133?

https://github.com/Redundakitties/colorful-minimalist/blob/main/hacks/sideberyModsLeftSlide.css
Looks like it won't get updated.

**Comment by markcst** [comment]
> Anyone knows how can I fix this code so it works with FF133?
> 
> https://github.com/Redundakitties/colorful-minimalist/blob/main/hacks/sideberyModsLeftSlide.css Looks like it won't get updated.

After 133 udpate Sidebery seems broken to me too. It won't expand sidebar, nor hide the top tab bar. I toggled it several times, but looks like something went wrong after that recent update (?)

**Comment by alephpi** [comment]
same issue after the update of FF133

**Comment by alephpi** [comment]
These two commits https://github.com/bmFtZQ/edge-frfox/commit/10c883cf56838c9cd6eb64b4865cc3cea1f62c5c and https://github.com/bmFtZQ/edge-frfox/commit/e36eec06b0d1e4ecef1e6052ecd132efbb732e58 should be helpful 

Seems FF133 has made a breaking change of window control.

**Comment by ckuma** [comment]
FWIW I had a similar issue and narrowed it down to the userChrome.css (i.e. the css file you've likely modified in your `about:profiles` > Profile folder > chrome subfolder > userChrome.css).  
Specifically what refers to the sidebar.  
Posting here in case this helps anybody else.

In my case the following for sidebar-box was helpful (explicitly adding the sidebar-box:hover) :
```css
#sidebar-box {
  --uc-sidebar-width: 36px;
  --uc-sidebar-hover-width: 600px;
  --uc-autohide-sidebar-delay: 0ms;
  position: relative;
  min-width: var(--uc-sidebar-width) !important;
  width: var(--uc-sidebar-width) !important;
  max-width: var(--uc-sidebar-width) !important;
  z-index: 1;
}

/* Add hover state to expand the sidebar */
#sidebar-box:hover {
  min-width: var(--uc-sidebar-hover-width) !important;
  width: var(--uc-sidebar-hover-width) !important;
  max-width: var(--uc-sidebar-hover-width) !important;
}

/* Optional: Add transition delay when moving mouse away */
#sidebar-box:not(:hover) {
  transition-delay: var(--uc-autohide-sidebar-delay);
}
```
