### ISSUE TITLE
The wiki suggestion to use "dynamic native tabs" using userChrome.css doesn't work with firefox 133

### ISSUE THREAD

**Issue by ricardoseriani** [mbnuqw/sidebery#1889]
### Steps to reproduce

- Open Firefox in a new profile
- Install Sidebery
- Enable using userChrome.css
- Configure userChrome.css and sidebery like https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)#dynamic-native-tabs

### Actual behavior

When you open firefox 133 the tabs are not hidding when Sidebery is opened

### Expected behavior

Firefox tabs should be hide when Sidebery is open.
After some research, I found that the `#titlebar` "selector" is removed from this version.
I tried to update the userChrome.css and get to a new version that is working for me, but I can't change or submit a PR to change the wiki.
All that it's need is to update the selector to `.toolbar-items` like the following snippet.

```
#main-window .toolbar-items {
    overflow: hidden;
    transition: height 0.3s 0.3s !important;
}

/* Default state: Set initial height to enable animation */
#main-window .toolbar-items {
    height: 3em !important;
}

#main-window[uidensity="touch"] .toolbar-items {
    height: 3.35em !important;
}

#main-window[uidensity="compact"] .toolbar-items {
    height: 2.7em !important;
}

/* Hidden state: Hide native tabs strip */
#main-window[titlepreface*="[Sidebery]"] .toolbar-items {
    height: 0 !important;
}

/* Hidden state: Fix z-index of active pinned tabs */
#main-window[titlepreface*="[Sidebery]"] #tabbrowser-tabs {
    z-index: 0 !important;
}
```

Please, note that I only tested on my machine and I'm no expert in CSS.

### System

Xubuntu 22.04

### Firefox version

133.0

### Sidebery version

5.2.0

**Comment by cem-okulmus** [comment]
Even when using this exact userChrome snippet, I still see Firefox bringing up the native tabs. It even shows Sideberry as a "sidebar extension", so this looks like it is almost hard-coded behaviour to have them both visible (which is pretty strange, clearly the point should be that Firefox hands off things to the dedicated "sidebar extension" then). I would suspect this is a bug. 


I should perhaps mention that I am using the "vertical tabs" option inside Firefox, as that also fixes things like window controls. Under horizontal tabs (and with sidebar.revamp set to false), I think this fix works.

**Comment by oktayacikalin** [comment]
I'm using horizontal tabs with sidebery. That fix above works fine in 133 using Gnome.

I'm also using the [firefox-gnome-theme](https://github.com/rafaelmardojai/firefox-gnome-theme/) and setting the sizes to 2.7em, 3.05em and 2.4em seems to fit better.

**Comment by cem-okulmus** [comment]
> I'm using horizontal tabs with sidebery. That fix above works fine in 133 using Gnome.
> 
> I'm also using the firefox-gnome-theme and setting the sizes to 2.7em, 3.05em and 2.4em seems to fit better.

Yeah, I decided to switch to  horizontal tabs. Long-term, I think now that Firefox does support vertical stuff natively, perhaps Firefox could just allow extensions to swap in their own side bars instead of the native vertical bar, which would be the best of both world, where you get custom sidebar  extensions without having to mess with userChrome at all.

**Comment by ricardoseriani** [comment]
> > I'm using horizontal tabs with sidebery. That fix above works fine in 133 using Gnome.
> > I'm also using the firefox-gnome-theme and setting the sizes to 2.7em, 3.05em and 2.4em seems to fit better.
> 
> Yeah, I decided to switch to horizontal tabs. Long-term, I think now that Firefox does support vertical stuff natively, perhaps Firefox could just allow extensions to swap in their own side bars instead of the native vertical bar, which would be the best of both world, where you get custom sidebar extensions without having to mess with userChrome at all.

Please, although I have not mentioned, be aware that you have to set the configuration `preface value` to `[Sidebery]` inside `Sidebery configuration -> General`.
By the way, my Firefox doesn't have an option to enable vertical support for tabs in the current release, only in the nightly release.
But I agree that will be awesome if Firefox allow extension to swap with the native bar.

**Comment by winter-again** [comment]
I found that this appears to work (using empty char for the preface). I used `TabsToolbar` instead of `titlebar`.

```
#main-window[titlepreface*="​"] #TabsToolbar {
    /* height: 0 !important; */
    visibility: collapse;
}
```

**Comment by emiliopedrollo** [comment]
Here's some css with animations working

```css
#main-window #TabsToolbar {⤶
··transition: visibility 0s 0s;⤶
}⤶
#main-window #TabsToolbar .toolbar-items {⤶
··overflow: hidden;⤶
··transition: height 0.3s 0.3s !important;⤶
}⤶
/* Default state: Set initial height to enable animation */⤶
#main-window #TabsToolbar .toolbar-items { height: 40px !important; }⤶
/* Hidden state: Hide native tabs strip */⤶
#main-window[titlepreface*="<200b>"] #TabsToolbar { visibility: collapse; transition: visibility 0s 0.6s !important }⤶
#main-window[titlepreface*="<200b>"] #TabsToolbar .toolbar-items { height: 0 !important; }⤶
/* Hidden state: Fix z-index of active pinned tabs */⤶
#main-window[titlepreface*="<200b>"] #tabbrowser-tabs { z-index: 0 !important; }⤶
```
