### ISSUE TITLE
Use "system-ui" generic font family as default sidebar content font

### ISSUE THREAD

**Issue by hdk5** [mbnuqw/sidebery#2031]
### Description

On Windows, with all settings at default, the current `sans-serif` value picks "Arial" for the sidebar content, while the rest of Firefox's UI uses "Segoe UI", creating an inconsistency. Using `system-ui` as the default font-family would better match the browser's native appearance.

**Comment by dexeonify** [comment]
Just updated to the nightly build and noticed this change.
Previously, when the font is set to `sans-serif`, Sidebery would respect Firefox's font settings in `about:preferences`. As an unintended consequence, this allowed me to customise all of Sidebery UI's font in one place.
![about:preference](https://github.com/user-attachments/assets/83b8f291-6791-4602-a202-963fb0694bb8)

I don't expect this behaviour to be reverted because using `system-ui` is more "correct" and ensures consistency with the rest of Firefox UI. I'm just wondering if there's a simpler way to modify Sidebery's font? Currently, I can restore the previous behaviour with the following CSS:
```css
#root {
    --tabs-font: 0.85rem sans-serif;
    --tabs-count-font: 0.5625rem sans-serif;
    --bookmarks-bookmark-font: 0.9375rem sans-serif;
    --bookmarks-folder-font: 0.9375rem sans-serif;
    --ctx-menu-font: 0.875rem sans-serif;
}
```
Maybe there should be a setting to change the font in Sidebery settings under Appearance, like font size?
