### ISSUE TITLE
Optional changing station titlePreface on extension opening/close for easy hiding horizontal tabs

### ISSUE THREAD

**Issue by AlexBeLi** [mbnuqw/sidebery#214]
By using rule like this in userChrome.css
```css
#main-window[titlepreface*="[Sideberry] "] #TabsToolbar {
  visibility: collapse !important;
}
```
