### ISSUE TITLE
Add simple title to panels

### ISSUE THREAD

**Issue by denemier** [mbnuqw/sidebery#218]
## Description
when i am viewing vertical panels its very hard to see the difference, i dont want mouse over to see the panel icons label, please add a small title.

this is must have please it would take maybe 1 minute for you

**Comment by mbnuqw** [comment]
Do you mean something like that? (like in Tree Tabs)

![screenshot-2020-05-06 21:03:05](https://user-images.githubusercontent.com/6276694/81200224-1ae54980-8fdd-11ea-9a1e-a207dbb42614.png)

**Comment by denemier** [comment]
Yes but, in PCB board design industry there is always a user experience rule in mind, because vertical text makes neck pain, horizontal texts are better for long work time (considering this as productivity software).

So I had similar type vertical panel texts(like your given image) in treetabs which gives us neck pain, but since you already have developed icon system to distinguish panels easily, i have designed icon+text version sample image below.
Let me know if something doesnt work with backend side or your ui standarts.

![Desktop - Light](https://user-images.githubusercontent.com/63566495/81255429-46485280-9036-11ea-911e-71101f6f2962.png)

**Comment by mbnuqw** [comment]
"vertical text makes neck pain"
Agreed, on the other hand horizontal text makes vertical navigation bar too thick and this can be problematic for users with the limited horizontal space.

As a workaround, I can render the panel names hidden by default, so users will be able to style navigation bar with their own css in their preferred way.

**Comment by denemier** [comment]
yes that would work for me thanks

**Comment by Nico207** [comment]
Hi @mbnuqw 

I tried to display the panel title with a custom css, without any result...
Can you tell me what should be done in the css to have a result like your first screenshot?

Thank you!

**Comment by mbnuqw** [comment]
Available in v4.9.1
Custom CSS (Sidebery settings > Styles editor):
```css
#root {
  --nav-btn-width: 22px;
}

.NavigationBar .panel-btn {
  display: flex;
  flex-direction: column-reverse;
  padding: 5px 0;
  height: auto;
}

.NavigationBar .panel-btn svg,
.NavigationBar .panel-btn img,
.NavigationBar .panel-btn .update-badge,
.NavigationBar .panel-btn .ok-badge,
.NavigationBar .panel-btn .err-badge,
.NavigationBar .panel-btn .progress-spinner {
  display: none;
}


.NavigationBar .panel-btn .progress-spinner {
  display: none;
}

.NavigationBar .panel-btn .len {
  position: relative;
  font-size: 9px;
  writing-mode: sideways-lr;
  text-orientation: mixed;
  background-color: transparent;
  padding: 0;
  top: 0;
  right: 0;
}

.NavigationBar .panel-btn .name {
  position: relative;
  display: block;
  padding: 3px 0 0;
  font-size: 13px;
  color: var(--container-fg, var(--nav-btn-fg));
  writing-mode: sideways-lr;
  text-orientation: mixed;
}
```
