### ISSUE TITLE
Feature Request: Dividers for pinned tabs

### ISSUE THREAD

**Issue by mbrasch** [mbnuqw/sidebery#236]
It would be very helpful if one could use dividers (or something like this) to group pinned tabs. I have ca. 40 of them. :)

**Comment by mbnuqw** [comment]
Unfortunately this is not possible with current internal structure of pinned tabs.
Workarounds:
- Sort out pinned tabs in different panels
- Try to use custom css to create divider for n-th pinned tab (for static pinned tabs). e.g. adding extra space after second pinned tab:
  ```css
  .PinnedTab:nth-child(2) {
    margin-bottom: 8px;
  }
  ```

**Comment by lmBored** [comment]
What I do is that adding background to pinned tabs:

```css
.Tab[data-pin="true"]{
	border: 1px solid rgba(255, 255, 255, 0.3);
	background-color: rgba(176, 251, 253, 0.2);
	border-radius: 10px;
	margin: 0px 2.7px 1.5px 0px;
}
```

And it would look like this:
<img width="267" alt="image" src="https://github.com/user-attachments/assets/109dde70-02f8-4cda-8360-e725d5d24bb4" />
