### ISSUE TITLE
color of the text of an unloaded tab

### ISSUE THREAD

**Issue by a-mann** [mbnuqw/sidebery#345]
Please add to the styles the ability to set the color of the text of an unloaded tab. 
![Снимок экрана от 2021-02-22 12-51-15](https://user-images.githubusercontent.com/6555992/108678287-b7e18680-750c-11eb-9cd7-70a77ae82d84.png)

Such as LodashDocumentation in the screenshot

**Comment by mbnuqw** [comment]
As a workaround it can be set via custom css (Sidebery settings / Appearance / Edit styles):
```css
.Tab[data-discarded="true"] .title {
  color: #ffaf00;
}
```

**Comment by Qwerty-Space** [comment]
Is it possible to make them not dim as well?

**Comment by tbruckmaier** [comment]
@Qwerty-Space this can be achieved like this:
```css
.Tab[data-discarded="true"] > .lvl-wrapper > .fav,
.Tab[data-discarded="true"] > .lvl-wrapper > .t-box,
.Tab[data-discarded="true"] > .lvl-wrapper > .ctx {
  opacity: 1;
}
```

(overrides the styles from https://github.com/mbnuqw/sidebery/blob/e8ac22c2c4a0bb339d53c5f2b46c5626e26a9012/src/styles/themes/default/tabs.tab.styl#L57-L61 )

**Comment by davidleejy** [comment]
> Please add to the styles the ability to set the color of the text of an unloaded tab. ![Снимок экрана от 2021-02-22 12-51-15](https://user-images.githubusercontent.com/6555992/108678287-b7e18680-750c-11eb-9cd7-70a77ae82d84.png)
> 
> Such as LodashDocumentation in the screenshot

Seconding this :) Personally having trouble reading light grey text on dark grey background probably due to my screen's poor contrast.

**Comment by valadaptive** [comment]
In v5, the class names have changed slightly:

```css
.Tab[data-discarded="true"] > .body > .fav,
.Tab[data-discarded="true"] > .body > .t-box,
.Tab[data-discarded="true"] > .body > .ctx {
  opacity: 1;
}
```
