### ISSUE TITLE
Make the container color bar more visible

### ISSUE THREAD

**Issue by xlucas** [mbnuqw/sidebery#348]
## Description

I find the color bar not easy to spot when you are using the dark theme and you stumble on a page with a white background because the contrast is so high that the bar is almost not visible as it is displayed on the border separating the side bar from the web page.

Maybe it would be nice to be able to move the color bar to the left or choose a thicker one to tackle this?

**Comment by mbnuqw** [comment]
To increase width of the container mark try this custom css (Sidebery settings > Appearance > Styles editor):
```css
.Tab .ctx {
  width: 3px;
}
```

To move it to the left:
```css
.Tab .ctx {
  right: auto;
  left: 2px;
  box-shadow: none;
}
```
