### ISSUE TITLE
Tab Favicons on the Right

### ISSUE THREAD

**Issue by Hayafumi** [mbnuqw/sidebery#353]
Can it be a option to put Tab Favicons of the right side of the sidebar?

**Comment by mbnuqw** [comment]
Try this custom css (Sidebery settings > Appearance > Styles editor)
```css
.Tab .fav {
  order: 1;
}

.Tab .title {
  padding-left: 8px;
}

.Tab .close {
  right: 24px;
}
```

![screenshot-2021-03-26 17:20:06](https://user-images.githubusercontent.com/6276694/112630541-89cacb80-8e57-11eb-81b5-716be7c38501.png)
