### ISSUE TITLE
Auto adjust tab title with its width

### ISSUE THREAD

**Issue by kushraj** [mbnuqw/sidebery#361]
## Description
![image](https://user-images.githubusercontent.com/36916613/111344334-4bd4e700-86a2-11eb-8fe2-39dc9bfefb91.png)
Is there any way I can make tab title text dynamic ?

above image should somewhat look like this depending on the sidebar width

![image](https://user-images.githubusercontent.com/36916613/111345127-fd741800-86a2-11eb-9fa8-82ce9d81206b.png) reddit : the front page of
the internet

**Comment by mbnuqw** [comment]
You can try this custom css (Sidebery settings > Appearance > Sidebar custom CSS):
```css
#root {
  --tabs-height: 36px !important;
  --tabs-title-padding: 8px;
  --tabs-font-size: 12px;
  --tabs-title-lines: 2;
}

.Tab .t-box {
  align-items: center;
  max-height: calc(var(--tabs-height) - var(--tabs-title-padding));
  overflow: hidden;
}

.Tab .title {
  font-size: var(--tabs-font-size);
  white-space: pre-wrap;
  line-height: calc((var(--tabs-height) - var(--tabs-title-padding)) / var(--tabs-title-lines));
}
```
![screenshot-2021-03-26 16:23:48](https://user-images.githubusercontent.com/6276694/112624797-e32efc80-8e4f-11eb-8759-734d822065df.png)
