### ISSUE TITLE
Dim unloaded (pinned) tabs

### ISSUE THREAD

**Issue by Staedie** [mbnuqw/sidebery#380]
## Description
Would it be possible to have the option of dimming the favicons of unloaded tabs, including pinned tabs? Vivaldi for example has this feature and its very helpful. Thank you!

**Comment by sctanf** [comment]
Unloaded tabs, pinned or otherwise, already have dimmed favicons.

**Comment by Staedie** [comment]
Thanks for the response! For unloaded pinned tabs, I can't see dimmed favicons. But probably I have to look better for an option in Firefox itself (about:config) to enable this feature.

**Comment by mbnuqw** [comment]
As @sctanf mentioned, favicons of unloaded pinned tabs are also dimmed. You can try to change default styles with custom css (in Sidebery settings / Appearance / Edit styles), e.g.:
```css
.PinnedTab[data-discarded="true"] {
  opacity: .4;
  filter: grayscale(0.5);
}

.Tab[data-discarded="true"] .fav,
.Tab[data-discarded="true"] .t-box {
  opacity: .4;
  filter: grayscale(0.5);
}
```

Also note that sidebery can't unload an active tab.
