### ISSUE TITLE
Unloaded tabs (unpinned) do not have dimmed container indicators

### ISSUE THREAD

**Issue by sctanf** [mbnuqw/sidebery#381]
## Steps to reproduce
Open a few tabs in containers
Pin one tab
Unload all tabs

## Expected behavior
All tabs have dimmed container indicators 

## Actual behavior
Only pinned tabs have dimmed container indicators

## Environment info
OS:  Windows 10 21H1
Firefox version:  88
Addon version:  4.9.4

<details><code>

</code></details>

**Comment by mbnuqw** [comment]
Thanks for the report. Temporary fix with custom css:
```css
.Tab[data-discarded="true"] .ctx {
  opacity: .5;
}
```
