### ISSUE TITLE
Hide sidebar top-menu only at sidebery (userChrome.css wiki)

### ISSUE THREAD

**Issue by OctavioBR** [mbnuqw/sidebery#448]
I'd suggest to include in the wiki, the option of [hiding sidebar top-menu](https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)#hide-sidebar-top-menu) **only** for sidebery, as follows:
```css
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"] #sidebar-header {
  display: none;
}
```
