### ISSUE TITLE
Better CSS for hiding the original tab bar when Sideberry is open

### ISSUE THREAD

**Issue by ShahriarKh** [mbnuqw/sidebery#458]
```css
#main-window #tabbrowser-tabs {
   transition: opacity .3s .3s !important;
 }
 
 #main-window[titlepreface*="XXX"] #tabbrowser-tabs {
   opacity: 0;
 }
```

I'm not sure if it's a good place to share this, but I'm just suggesting a more smooth tab bar hiding compared to [this](https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)#dynamic-native-tabs).
