### ISSUE TITLE
Change new tab icon in sidebar

### ISSUE THREAD

**Issue by Iss-in** [mbnuqw/sidebery#497]
Is it possible to change the new tab icon in sidebar which is currently a firefox icon. using css ?

**Comment by nearcatch** [comment]
Add the below to Sidebery css to change the favicon for new tabs to the current browser's icon. Change `background` url and `--custom-favicon-size` to what you like.

```CSS
.Tab[title^="New Tab"][title$="about:newtab"] .fav svg {
   display:none;
}
.Tab[title^="New Tab"][title$="about:newtab"] .fav .placeholder::after {
    --custom-favicon-size: 16px;
    content: '';
    position: absolute;
    pointer-events: none;
    touch-action: none;
    background: url("chrome://branding/content/icon32.png") no-repeat;
    background-size: var(--custom-favicon-size);
    height: var(--custom-favicon-size);
    width: var(--custom-favicon-size);
}
```
