### ISSUE TITLE
Make favicon visible under arrow of folded tab

### ISSUE THREAD

**Issue by janhieber** [mbnuqw/sidebery#531]
## Description
When a tab has children and is collapsed, the arrow is shown. This makes the favicon very difficult to identify which leaves only the tabs title text to see what it is.

![sidebery_000](https://user-images.githubusercontent.com/1897479/145582856-b11d1bad-0165-47d5-88e8-f19c39d990b8.jpg)

Can we somehow make the symbol/favicon visible again?

**Comment by nearcatch** [comment]
You can add this to your Sidebery CSS and it will hide the arrow and number when the tab isn't hovered and set the favicon opacity to 1.

```css
.Tab[data-parent][data-folded]:not(:hover) .exp,
.Tab[data-parent][data-folded]:not(:hover) .child-count {
    display: none;
}
.Tab[data-parent][data-folded]:not(:hover) .fav > img {
    opacity: 1;
}
```
