### ISSUE TITLE
Adding margins around  tabs break tab dragging indicator

### ISSUE THREAD

**Issue by afraidofmusic** [mbnuqw/sidebery#542]
## Steps to reproduce
1. Add margins around tabs by adding
```
.Tab {
  margin: 5px;
}
```
2. Drag tabs to reorder

## Expected behavior
Moving the tab to the desired location.

## Actual behavior
The indicator isn't aligned with the tabs as shown below. Making it difficult to predict where the tab will land.
https://imgur.com/a/haeQEMo

## Environment info

OS:  Windows 10
Firefox version:  95.0.2
Addon version:  4.10.0

## There rest of the css
```
#root {
  --tabs-font: 10pt Segoe UI;
  --tabs-count-font: .625rem Segoe UI;
  --bookmarks-bookmark-font: .875rem Segoe UI;
  --bookmarks-folder-font: 10pt Segoe UI;
  --tabs-height: 32px;
}
@media screen and (max-width: 49px) {
  #root {
    --tabs-indent: unset;
  }
}
@media screen and (max-width: 49px) {
  .Tab .audio {
    margin-left: -15px;
    transform: scale(.80);
    z-index: 99 !important;
  }
}

.Tab .fav {
  width: 18px;
  height: 18px;
  margin: 0 7px 0 6px;
}

.Tab .placeholder > svg {
  width: 18px;
  height: 18px;
}

.Tab {
  margin: 8px;
  border-radius: 5px;
  width: unset;
}

@media (prefers-color-scheme:light) {
  .Tab[data-active] {
    box-shadow: 0px 0px 8px rgba(155, 155, 155, 0.3);
  }
}

@media (prefers-color-scheme:dark) {
  .Tab[data-active] {
    box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.2);
  }
}
```

<details><code>

</code></details>

**Comment by mbnuqw** [comment]
Positions for drag and drop pointer are calculated from css var --tabs-height which is the reason of this behavior.
You can use absolutely positioned layer to create desired form of the tabs.
Something like that:
```css
#root {
  --tabs-font: 10pt Segoe UI;
  --tabs-count-font: .625rem Segoe UI;
  --bookmarks-bookmark-font: .875rem Segoe UI;
  --bookmarks-folder-font: 10pt Segoe UI;
  --tabs-height: 32px;
}
@media screen and (max-width: 49px) {
  #root {
    --tabs-indent: unset;
  }
}
@media screen and (max-width: 49px) {
  .Tab .audio {
    margin-left: -15px;
    transform: scale(.80);
    z-index: 99 !important;
  }
}

.Tab .fav {
  width: 18px;
  height: 18px;
  margin: 0 7px 0 6px;
}

.Tab .placeholder > svg {
  width: 18px;
  height: 18px;
}

/* Reset default styles */
.Tab[data-active] {
  background-color: transparent;
}

/* Background layer */
.Tab .lvl-wrapper:after {
  content: '';
  position: absolute;
  top: 3px;
  left: 2px;
  width: calc(100% - 4px);
  height: calc(100% - 6px);
  border-radius: 5px;
  z-index: -1;
}
.Tab[data-active] .lvl-wrapper:after {
  background-color: #000;
}

@media (prefers-color-scheme:light) {
  .Tab[data-active] .lvl-wrapper:after {
    box-shadow: 0px 0px 8px rgba(155, 155, 155, 0.3);
  }
}

@media (prefers-color-scheme:dark) {
  .Tab[data-active] .lvl-wrapper:after {
    box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.2);
  }
}
```
