### ISSUE TITLE
Panels: have the option to have the full name

### ISSUE THREAD

**Issue by jgournet** [mbnuqw/sidebery#640]
## Description
Coming from Tree Tabs, their panels are with full names.
Would it be possible to have the option to do the same in sidebery ?

**Comment by mbnuqw** [comment]
I'll consider adding this option for the vertical navigation bar in v5. For now, you can use this custom CSS (Sidebery settings > Styles editor) (for v4):
```css
#root {
  --nav-btn-width: 24px;
  --nav-btn-height: 24px;
}

.NavigationBar .panel-btn {
  display: flex;
  flex-direction: column-reverse;
  padding: 8px 0;
  height: auto;
}

.NavigationBar .panel-btn[data-type="add"] {
  height: var(--nav-btn-height);
}

.NavigationBar .panel-btn[data-type="tabs"] svg,
.NavigationBar .panel-btn[data-type="default"] svg,
.NavigationBar .panel-btn[data-type="bookmarks"] svg,
.NavigationBar .panel-btn img,
.NavigationBar .panel-btn .update-badge,
.NavigationBar .panel-btn .ok-badge,
.NavigationBar .panel-btn .err-badge,
.NavigationBar .panel-btn .progress-spinner {
  display: none;
}


.NavigationBar .panel-btn .progress-spinner {
  display: none;
}

.NavigationBar .panel-btn .len {
  position: relative;
  font-size: 12px;
  writing-mode: sideways-lr;
  text-orientation: mixed;
  background-color: transparent;
  padding: 0;
  top: 0;
  right: 0;
  opacity: .7;
}

.NavigationBar .panel-btn .name {
  position: relative;
  display: block;
  padding: 6px 0 0;
  font-size: 14px;
  color: var(--container-fg, var(--nav-btn-fg));
  writing-mode: sideways-lr;
  text-orientation: mixed;
}
```
