### ISSUE TITLE
Styling option to match native sidebars

### ISSUE THREAD

**Issue by 00madz** [mbnuqw/sidebery#71]
Firstly, thank you for all your wonderful work on Sidebery. 
Not sure if it's possible for extensions, but I'd like the ability to have the styling and background simply match the native sidebars - the background seems to change based on OS colours (on OSX) and has some sort of transparency/gradient type effect but looks different depending on whether the window is maximised or not. I don't know whether sidebery can have a "transparent background" option which will result in it looking like a normal sidebar or if the extensions just eg start with a white surface?
It'd also be nice if the font and font size could match standard sidebars by default.

**Comment by mbnuqw** [comment]
Unfortunately, transparent background of sidebar is not possible and styling of scrollbars in Firefox is pretty limited. Though, there are some tricks with userChrome.css that allows you to change sidebar width depending on window state.
E.g. this code will shrink sidebar in 32px bar in full-screen mode and restore it on mouse hover:
```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
#sidebar-header {
  display: none;
}
#main-window[inFullscreen] #sidebar-box {
  position: fixed;
  display: block;
  min-width: 0px !important;
  max-width: none !important;
  width: 32px !important;
  height: 100%;
  overflow: hidden;
  box-shadow: 0 0 8px 0 #00000064, 1px 0 0 0 #212121;
  transition: all 0.12s;
}
#main-window[inFullscreen] #sidebar {
  position: absolute;
  min-width: 0px !important;
  max-width: none !important;
  left: 0;
  top: 0;
  right: auto;
  bottom: auto;
  width: 32px;
  height: 100%;
}
#main-window[inFullscreen] #sidebar:before {
  content: '';
  position: absolute;
  background-color: #323232;
  display: block;
  top: 0;
  left: 0;
  width: 32px;
  height: 100%;
  z-index: 1;
  transition: transform 0.12s;
}
#main-window[inFullscreen] #sidebar-box:hover {
  width: 250px !important;
}
#main-window[inFullscreen] #sidebar-box:hover #sidebar:before {
  transform: translateX(-100%);
}
#main-window[inFullscreen] #sidebar-box:hover #sidebar {
  width: 250px !important;
}
```

About the fonts - in next version you will be able to customize styles (including fonts) of any Sidebery part (sidebar itself, group page, etc...).
