### ISSUE TITLE
Ability to remove blue dot from pinned tabs

### ISSUE THREAD

**Issue by toylatte** [mbnuqw/sidebery#712]
Is there a way to disable the blue dot that appears when the title of a pinned tab changes? I have attached a screenshot of what I'm talking about.

<img width="38" alt="image" src="https://user-images.githubusercontent.com/65741403/182086156-74eef523-8f04-4932-a8cf-0b04cda96b96.png">

**Comment by mbnuqw** [comment]
Duplicate of #365
(will be added in v5.0.0b26)

For now workaround for v5:
```css
.Tab[data-updated="true"] .fav .badge {
  display: none;
}

.Tab[data-updated="true"] .fav img,
.Tab[data-updated="true"] .fav svg {
  mask: none;
}
```

Only for pinned tab:
```css
.Tab[data-updated="true"][data-pin="true"] .fav .badge {
  display: none;
}

.Tab[data-updated="true"][data-pin="true"] .fav img,
.Tab[data-updated="true"][data-pin="true"] .fav svg {
  mask: none;
}
```
(workaround for v4 is in an issue above)
