### ISSUE TITLE
Is there any way to move Sidebar up or down? Or is it only to the right?

### ISSUE THREAD

**Issue by prfctvaccum** [mbnuqw/sidebery#717]
it's better for my workflow, to have everything at the bottom or top.

thanks!

**Comment by mbnuqw** [comment]
Natively, Firefox sidebar can be placed only at the left or right side, everything beyond that requires [userChrome.css](https://www.reddit.com/r/FirefoxCSS/wiki/index/tutorials) customization.

Example of turning a sidebar into a bottombar
```css
hbox#browser {
  display: flex;
  flex-direction: column-reverse;
}

#sidebar-box.sidebar-box {
  flex-grow: 1;
  max-width: 100%;
}

#sidebar-box.sidebar-box #sidebar {
  max-width: 100%;
}

#sidebar-splitter.sidebar-splitter {
  display: none;
}

vbox#appcontent {
  flex-grow: 1;
}
```

![screenshot](https://user-images.githubusercontent.com/6276694/185431147-f823b849-ed22-412e-9224-dd63ad742fe3.png)
