### ISSUE TITLE
Style the sidebar top menu

### ISSUE THREAD

**Issue by WyrdByWord** [mbnuqw/sidebery#741]
Is there a way to change the color of the Sidebar top menu (with the Sidebery icon, etc)? I'd like to change this area to match my scheme:

![CleanShot 2022-08-29 at 10 14 58](https://user-images.githubusercontent.com/111014986/187257941-9b5fdacd-f2f1-4890-a979-8e9636f14e8f.png)

Thanks!

**Comment by jathek** [comment]
This is a default Firefox element, not from Sidebery, so you have to change it in userChrome.css.

```css
#sidebar-box {
  --sidebar-background-color: blue !important;
}
```
