### ISSUE TITLE
Use larger favicons when available?

### ISSUE THREAD

**Issue by jathek** [mbnuqw/sidebery#784]
I use custom css for the sidebar to increase the size of tabs and favicons. Sometimes the favicon gets blurry as it's a 16x16 image that gets scaled up. Other times a site's favicon seems to be using a high-res version. For some sites, I can see in the code that there is a high-res version that Firefox/Sidebery is not using. Is there a way to make Firefox/Sidebery use high-res favicons when available?

**low res:**
![image](https://user-images.githubusercontent.com/692914/193392544-ab6e1b25-0af7-4ef4-b86a-b2e045d6e4cf.png)

**high-res available in page source:**
![image](https://user-images.githubusercontent.com/692914/193392564-a3840a37-6338-44bf-bb36-df1da47dbba9.png)

**page after I edited source via inspector to use high-res icon for low-res size:**
![image](https://user-images.githubusercontent.com/692914/193392581-f8ca3221-f9f3-4c0c-a0cc-6a25059afbff.png)
![image](https://user-images.githubusercontent.com/692914/193392590-e0d20abb-944b-4ca0-93cd-5f65fab5a68f.png)

[sample link for above](https://support.mozilla.org/en-US/questions/1200030)
css code to create the bigger sizes I have:
```css
#root {
    --tabs-height: 42px;
    --tabs-pinned-height: var(--tabs-height);
    --tabs-pinned-width: var(--tabs-height);
    --selected-bg: rgba(0, 108, 151, 0.8) !important;
    --selected-border: var(--selected-bg) !important;
    --fav-size: 24px;
  }

  .Tab .fav {
    width: var(--fav-size);
    height: var(--fav-size);
  }
  .Tab .fav > .fav-icon {
    width: var(--fav-size);
    height: var(--fav-size);
    /*  filter: drop-shadow(0px 0px 4px rgba(220,220,220,0.3)) !important;*/
  }
```
