### ISSUE TITLE
[Feature request] Increase "collapse/expand branch" hitbox 

### ISSUE THREAD

**Issue by Elaws** [mbnuqw/sidebery#797]
## Description

Currently, a branch is collapsed and expanded only if we click on the little arrow at the left (unless you have "Auto-expand on activation", but it does not work for collapsing) :

![0_sidebery - Copie (2)](https://user-images.githubusercontent.com/52013479/194843648-a09f3f83-8b8d-4352-b950-8f29c320d2af.png)

It would make the UI more convenient to use if we could click on the whole tab line to collapse/expand a branch. The larger the hitbox, the better :

![0_sidebery - Copie](https://user-images.githubusercontent.com/52013479/194843780-c0d0d723-ef59-4171-8b02-48afa8c33a24.png)

Thanks !

**Comment by emvaized** [comment]
If we could click on the whole tab line to collapse/expand — then, where to click to just activate the tab without collapsing/expanding? 😏

And if the hit box would be some percent of tab's width, then it's not visually clear where the hitbox ends — this is not good from UX perspective.

However, it's possible to do via custom CSS – but it would be more tricky than some might expect, because of rotation animation being applied to the whole hitbox container `.exp` instead of only the icon inside it. This behavior should be overwritten as well, if you don't want the arrow to shift on rotation of this, no longer squarish, container.

Something like this:
```
/* Increase hit target width by 50px */
.Tab .fav .exp { width: calc(100% + 58px); }

/* Disable container rotation */
.Tab[data-parent="true"][data-folded="true"] .fav .exp { transform: none; }

/* Rotate the icon instead */
.Tab .fav .exp svg { transition: opacity var(--d-fast),transform var(--d-fast); }
.Tab[data-parent="true"][data-folded="true"] .fav .exp svg { transform: rotateZ(-90deg); }
```

**Comment by Elaws** [comment]
I really like your idea of increasing the hitbox size but still letting the possibility to click the tab without expanding/collapsing. 

Do you think there is a way to increase hitbox size proportionally to the size of the line ? So that, for example, it would always take half the line, not matter its size :

![0proto2](https://user-images.githubusercontent.com/52013479/195109817-69e25b86-a076-4986-b47f-95a64e6ed0e4.png)
![0proto1](https://user-images.githubusercontent.com/52013479/195109823-269e90eb-bd03-4b84-bf58-c2250456074b.png)

**Comment by emvaized** [comment]
Maybe. But then you'll need to increase the size of parent `.fav` container to always take 50% of tab's width, and handle proper positioning of all it's children elements – `.exp` arrow element, which should fill the width of `.fav` (but display arrow icon on the left), and `.fav-icon` and `.badge` elements, which should be limited by pixels and shown on the left.

**Comment by mbnuqw** [comment]
It's possible to use `vw` units instead of px to set the width of the hitbox: (updated @emvaized's snippet)
```css
/* Create hitbox */
.Tab .fav .exp:after {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 50vw;
  height: 100%;
  z-index: 100;
}

/* Disable container rotation */
.Tab[data-parent="true"] .fav .exp {
  transform: none !important;
}

/* Rotate the icon instead */
.Tab .fav .exp svg {
  transition: opacity var(--d-fast),transform var(--d-fast);
}
.Tab[data-parent="true"][data-folded="true"] .fav .exp svg {
  transform: rotateZ(-90deg);
}
```

Closing this issue as I don't plan to implement it and it has a workaround with the custom CSS.
