### ISSUE TITLE
Media screen queries don’t work anymore after updating to v5?

### ISSUE THREAD

**Issue by Keagel** [mbnuqw/sidebery#883]
## Steps to reproduce
- Use this simple custom CSS in the styles editor's `Sidebar` section with Sidebery v4 (you can change the max-width to check it doesn't work, in my case this is used to apply different CSS rules based on the sidebar's width as I edited userChrome.css to change the sidebar's width on hover):
```css
@media screen and (max-width: 47px) {
  #root {
    --tabs-indent: unset;
  }
}
```
- Upgrade to v5

## Expected behavior

Media query rules should be applied.

## Actual behavior

Media query rules aren't applied.

## Additional information

I'm not sure how it can even be related to Sidebery but the fact is when I take that rule out of the media query it does work. It worked fine right before upgrading. It works on my other instance of Firefox where I still have Sidebery v4. I can see that the custom CSS *is* in the `style` node when I debug the extension, but it just doesn't work.

**Comment by mbnuqw** [comment]
This happens because v5 has different `--tabs-indent` values for different density (default - `#root {...}`, compact - `#root[data-density="compact"] {...}`, ...etc), so you just need to increase specificity of selector e.g.:
```css 
@media screen and (max-width: 47px) {
  #root.Sidebar {
    --tabs-indent: unset;
  }
}
```

Also, I purposely comment out custom CSS on upgrade from v4 because there are a lot of differences in DOM structure (custom CSS for v4 will most likely be broken in v5)
