### ISSUE TITLE
have the audio icon be more noticeable 

### ISSUE THREAD

**Issue by microsuperman** [mbnuqw/sidebery#885]
Could it be possible to make the audio icon that appears when audio is playing from a tab more noticeable. 
![Screenshot](https://user-images.githubusercontent.com/11239180/208991559-b20bb4e8-f31b-4472-8405-9f2626f9726b.jpg)
Something like have it slowly flash or cycle through colors or maybe rocking back and forth.

**Comment by mbnuqw** [comment]
Not planned. You can use custom CSS (Sidebery settings / Styles editor):
```css
.Tab .-loud {
  animation: audio-animation 1s infinite;
}

@keyframes audio-animation {
  0% {
    transform: scale(0.9);
  }
  50% {
    transform: scale(1.2);
  }
  100% {
    transform: scale(1);
  }
}
```
or
```css
.Tab .-loud {
  animation: audio-animation 1s infinite;
}

@keyframes audio-animation {
  0% {
    fill: var(--title-fg);
  }
  50% {
    fill: var(--bg);
  }
  100% {
    fill: var(--title-fg);
  }
}
```
